name: Tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    name: Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.0", "8.1", "8.2", "8.3", "8.4"]
        typo3-version: ["11.5", "12.4", "13.4"]
        dependencies: ["highest", "lowest"]
        exclude:
          - php-version: "8.0"
            typo3-version: "12.4"
          - php-version: "8.0"
            typo3-version: "13.4"
          - php-version: "8.1"
            typo3-version: "13.4"
          - php-version: "8.4"
            typo3-version: "11.5"
          - php-version: "8.4"
            typo3-version: "12.4"
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: '127.0.0.1'
      typo3DatabaseUsername: root
      typo3DatabasePassword: root

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: none

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Install Composer dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: "--with=typo3/cms-core:^${{ matrix.typo3-version }}"

      # Run tests
      - name: Run tests
        run: composer test

  coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    env:
      typo3DatabaseName: typo3
      typo3DatabaseHost: '127.0.0.1'
      typo3DatabaseUsername: root
      typo3DatabasePassword: root

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2, php-coveralls/php-coveralls
          coverage: pcov

      # Start MySQL service
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start

      # Install Composer dependencies
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      # Run tests
      - name: Run tests
        run: composer test:coverage

      # Build coverage report
      - name: Generate coverage report
        run: php-coveralls -x .build/log/coverage/clover.xml -o .build/log/coverage/coveralls.json -v
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
